import type { Task, Metric } from "./llm-router";
export type { Task, Metric };
export type Model = { id: string; name: string; source: string; inputUsdPerMillion: number | null; outputUsdPerMillion: number | null; demoContextLimit: number | null; images: boolean | null; scores: Partial<Record<Task, number>>; agent: string | null; totalB: number | null; activeB: number | null; weights: string; role: string; speed: number | null; capturedAt: string; evidence: string; priceTier: string; sizeTier: string };
export type Request = { task: Task; mode: "quality" | "economy" | "speed" | "preference_demo"; inputTokens: number; outputTokens: number; budgetUsd: number; minScore: number; needsImages: boolean; privacy: "cloud_allowed" | "local_only"; allowArchived: boolean; excluded: string[]; preference: number; threshold: number; strongId: string; weakId: string; priceTier: string; sizeTier: string; weights: string; batchSize: number; minTokensPerSecond: number; operation: string };
export type Candidate = { model: Model; score: number; estimatedUsd: number; harness: string | null };
export type Result = { status: string; selected: Candidate | null; fallback: Candidate | null; ranked: Candidate[]; excluded: { id: string; name: string; reasons: string[] }[]; snapshotDate: string; metric: Metric | null; request: Request; reason: string; warnings: string[] };
export const models: readonly Model[];
export const tasks: readonly Task[];
export const modes: readonly Request["mode"][];
export const operations: readonly string[];
export const metrics: Record<Task, Metric | null>;
export const snapshotDate: string;
export const paper: string;
export const defaults: Readonly<Request>;
export const priceTiers: Record<string, string>;
export const sizeTiers: Record<string, string>;
export function validate(input: Partial<Request>): Request;
export function cost(model: Model, request: Pick<Request, "inputTokens" | "outputTokens"> & { batchSize?: number }): number | null;
export function shortlist(request: Partial<Request>): Model[];
export function route(request: Partial<Request>, now?: Date | string | number): Result;
export function classificationPayload(prompt: string, privacy?: Request["privacy"]): unknown;
export function parseClassification(response: unknown): Task;
export function exactOrder(text: string): { status: string; order: string | null; calls: number; note: string };
